
version: 2

sources:
  - name: raw
    database: employee_data
    schema: raw
    tables:
      - name: departments
      - name: departures
      - name: dept_emp
      - name: dept_manager
      - name: employees
      - name: salaries
      - name: titles
